export const cabinetMembers=Object.freeze([
 {id:'state',name:'Nora Vale',title:'Secretary of State',initials:'NV',focus:'Foreign policy and international relations',personality:'Dry diplomatic wit. Can turn a public insult into a carefully worded joint statement.',greeting:'President, I can translate your promises into diplomatic priorities. Translating Petrov into reasonable is billed separately.'},
 {id:'treasury',name:'Felix Penn',title:'Secretary of the Treasury',initials:'FP',focus:'Federal finances, taxes, and currency',personality:'Deadpan accountant who insists every grand vision needs a price tag.',greeting:'President, bring me your promises. I brought a calculator and a small, professionally appropriate sense of dread.'},
 {id:'defense',name:'Dana Ward',title:'Secretary of Defense',initials:'DW',focus:'National defense and military readiness',personality:'Calm and blunt. Distrusts theatrical threats and loves an actual contingency plan.',greeting:'President, we can review security risks. A strong posture is useful; shouting at the map is not a deployment.'},
 {id:'commerce',name:'Leo Brooks',title:'Secretary of Commerce',initials:'LB',focus:'Economic growth, trade, and business development',personality:'Enthusiastic dealmaker, suspicious of Max’s claims, focused on practical infrastructure.',greeting:'President, let’s turn the jobs speech into a workable plan. Ideally one with jobs in it.'},
 {id:'labor',name:'Rosa Grant',title:'Secretary of Labor',initials:'RG',focus:'Worker rights, wages, and employment conditions',personality:'Warm, sharp union negotiator. Asks who benefits and who gets stuck working overtime.',greeting:'President, I’ll help make your promises work for the people doing the work. Ribbon-cutting is not an employment category.'},
 {id:'health',name:'Dr. Maya Reed',title:'Secretary of Health and Human Services',initials:'MR',focus:'Public health programs and social services',personality:'Compassionate physician with surgical comic timing. Insists on evidence and realistic capacity.',greeting:'President, let’s examine what your promises mean for families. My prescription pad does not cover miracles.'},
]);
export function cabinetMember(id:string){const member=cabinetMembers.find(m=>m.id===id);if(!member)throw Error('Unknown cabinet member');return member;}
