import {revenueOutlook} from '../economy/revenue.ts';
import {strategicState,strategicPublicContext,securityOptions} from '../diplomacy/strategic.ts';
import type {World} from '../../../shared/schemas/oil-crisis.ts';
import {cabinetPromiseOverview,promiseGuidance} from '../cabinet/promises.ts';
import {localNewsEngine} from '../events/local-news.ts';
import {campaignRules} from '../campaign/campaign.ts';
import {electionRules} from '../election/election.ts';
import {worldEventEngine} from '../events/world-news.ts';
import {cabinetMember} from './cabinet-members.ts';
export {cabinetMembers,cabinetMember} from './cabinet-members.ts';
export type CabinetMessage={role:'user'|'assistant';text:string};
export interface CabinetVoice {line:string;replies:string[]}
export function validateCabinetMessages(value:unknown):CabinetMessage[]{
 if(!Array.isArray(value)||value.length>20)throw Error('Invalid cabinet history');
 return value.map(m=>{if(!m||!['user','assistant'].includes(m.role)||typeof m.text!=='string'||!m.text.trim()||m.text.length>(m.role==='user'?600:1800))throw Error('Invalid cabinet message');return {role:m.role,text:m.text.trim()};});
}
export function validateCabinetVoice(value:unknown):CabinetVoice{
 const v=value as CabinetVoice;if(!v||typeof v.line!=='string'||!v.line.trim()||v.line.length>1800||!Array.isArray(v.replies)||v.replies.length<2||v.replies.length>4||v.replies.some(r=>typeof r!=='string'||!r.trim()||r.length>160)||new Set(v.replies).size!==v.replies.length)throw Error('Invalid cabinet response');return {line:v.line,replies:[...v.replies]};
}
export function cabinetContext(world:World,id:string,messages:CabinetMessage[],promiseIndex?:number){return {revenue:revenueOutlook(world),strategic:strategicPublicContext(world),securityOptions:securityOptions(world),selectedPromise:promiseIndex===undefined?undefined:promiseGuidance(world,promiseIndex),promiseOwnership:cabinetPromiseOverview(world),rules:{baseOilDemand:6,shortageApprovalPenaltyPerUnit:3,dailyRevenue:3,studyCost:6,limits:'Petrovia is the only playable oil supplier. No domestic extraction, adjustable taxes, or alternative supplier mechanics exist yet. The Petrovia channel supports three-day supply, territorial commitments, observers, public recognition, and the supplied securityOptions. One order per day; all spending and signatures require player confirmation. Only the listed strategic orders are executable, never tactical deployments. Discuss these as future proposals only. Do not invent numeric effects.'},member:cabinetMember(id),campaign:campaignRules.context(world),state:world.state,election:electionRules.snapshot(world),news:worldEventEngine.context(world),localNews:localNewsEngine.context(world),publicOutcomes:world.events.filter(e=>!e.cabinetAssignment&&(!e.strategic||e.strategic.reports.length)&&(!e.diplomacy&&!e.sterling||e.diplomacy?.reply==='accept'||e.sterling?.reply==='fund')).slice(-6).map(e=>e.strategic?e.strategic.reports.map(r=>`${r.certainty}: ${r.facts}`):e.messages),conversation:validateCabinetMessages(messages)};}
export function offlineCabinet(world:World,id:string,promiseIndex?:number):CabinetVoice{
 if(promiseIndex!==undefined){const m=cabinetMember(id),p=promiseGuidance(world,promiseIndex);return {line:`${m.greeting}\n\nPromise: ${p.promise}\n${p.status}. ${p.blocker}\nNext: ${p.next.title}${p.next.cost?` · F${p.next.cost}`:''}.\n\nThis is an offline briefing. I can report the recorded progress; connect Claude to discuss feasibility. Advice does not enact policy.`,replies:['Can we actually do this?','What’s blocking us?','What should I do next?']};}
const s=strategicState(world);if(s&&['state','defense','treasury'].includes(id)){const context=strategicPublicContext(world)!;const advice=id==='state'?`Petrovia wants income, influence, security, and public credit. Offer a monitored territorial commitment in exchange for a supply contract or a conditional summit. Signing is separate from talking.`:id==='defense'?`Current recorded threat: ${s.homeland}. Unverified allegations are not confirmed attacks. ${securityOptions(world).filter(o=>!o.blocked).map(o=>`${o.title}: F$${o.cost}${o.oil?` and ${o.oil} barrels`:''}. ${o.hint}`).join(' ')||'No security order is available today.'}`:`Treasury: F$${world.state.treasury}. ${revenueOutlook(world).nextDay?`Next tax deposit: F$${revenueOutlook(world).amount} on day ${revenueOutlook(world).nextDay}, before overnight bills, plus F$3 daily revenue.`:'No further scheduled deposits before the election.'} ${s.treaty?`${s.treaty.status} contract: F$${s.treaty.terms.quantity*s.treaty.terms.price} each scheduled day, through day ${s.treaty.throughDay}. ${s.lastDelivery}`:'No signed supply contract.'} Keep funds for daily payments and deployment upkeep. An unpaid shipment transfers neither money nor oil.`;return {line:`${cabinetMember(id).greeting}\n\n${context.stage}. ${context.warning}.\n${advice}\n\nUse the Petrov channel to review exact terms and authorize actions. This advice changes nothing by itself.`,replies:['What terms could reduce the risk?','What can we afford?','What is confirmed, and what is only an allegation?']};}
const m=cabinetMember(id),promises=campaignRules.promises(world)?.promises??[];return {line:`${m.greeting}\n\n${promises.length?`Your campaign commitments are: ${promises.join('; ')}. We should clarify the intended outcome, check feasibility and cost, and then introduce a bill, negotiate its conditions and secure both chamber votes in Congress.`:'Record your three campaign promises first so we can review them together.'}\n\nThis is an offline briefing. Connect Claude for a response to your specific question. Advice here does not enact policy.`,replies:['Which promise needs attention first?','What are the costs and risks?','Give me a realistic next step.']};}
