import type { World } from '../../../shared/schemas/oil-crisis.ts';
export interface LocalBulletin {id:string;kind:string;day:number;headline:string;facts:string;stakes:string;community:string}
const stories:readonly Omit<LocalBulletin,'id'|'day'>[]=[
 {kind:'school-safety',community:'Cedar Falls',headline:'SCHOOL BOARD PAUSES AFTER SAFETY ALERT',facts:'Cedar Falls schools briefly paused classes after a credible safety alert. Students and staff were reunited with families; authorities report no injuries.',stakes:'Families want visible safety planning without turning every classroom into a checkpoint.'},
 {kind:'officer-shot',community:'Northpoint',headline:'NORTHPOINT OFFICER INJURED RESPONDING TO CALL',facts:'A Northpoint police officer was injured during a response. The investigation is active, and officials have not released a motive or suspect details.',stakes:'The city wants support for first responders while civil-rights groups ask for transparent review.'},
 {kind:'layoffs',community:'Lake Junction',headline:'LAKE JUNCTION FACTORY ANNOUNCES MASS LAYOFFS',facts:'A fictional appliance factory in Lake Junction announced hundreds of job cuts after losing a major contract.',stakes:'Workers want retraining and immediate relief; the governor wants the White House to announce a rescue before a plan exists.'},
 {kind:'hospital',community:'West Mercer',headline:'WEST MERCER HOSPITAL CUTS NIGHT CLINIC HOURS',facts:'West Mercer Medical says staffing shortages will reduce overnight clinic hours for two weeks.',stakes:'Local leaders want emergency staffing funds, while budget staff warn that every quick fix becomes a recurring bill.'},
];
export class LocalNewsEngine { next(world:World):LocalBulletin|undefined { const day=world.state.day+1;if(day<2||day%2!==0)return; const last=world.events.findLast(e=>e.localNews)?.localNews; const pool=stories.filter(s=>s.kind!==last?.kind);const chosen=pool[(day+world.events.length)%(pool.length||stories.length)]??stories[0];return Object.freeze({...chosen,id:`bull-${day}-${chosen.kind}`,day}); } context(world:World){return {bulletins:world.events.filter(e=>e.localNews).slice(-6).map(e=>e.localNews),rule:'BULL reports fictional local incidents without graphic detail. It does not invent casualties, suspects, motives, arrests, or completed policy responses.'};} }
export const localNewsEngine=new LocalNewsEngine();
