import type {World} from '../shared/schemas/oil-crisis.ts';
import type {StaffBrief} from '../server/src/ai/staff.ts';
import {campaignRules} from '../server/src/campaign/campaign.ts';
import {escapeHtml as e} from './conversation.ts';
export function campaignOpening(){return `<span class="case-tag">BEFORE THE INAUGURATION</span><h2>Three promises.<br>An entire presidency.</h2><p class="speech">What did you promise Freedoma? Be ambitious, practical, or spectacularly unreasonable. The world will remember—and reality gets a vote.</p><form id="campaign-form">${[0,1,2].map(i=>`<label for="promise-${i}">Campaign promise ${i+1}</label><textarea id="promise-${i}" required minlength="5" maxlength="240" rows="2" placeholder="${['Unicorns at every school','Affordable fuel for everyone','Make public transport reliable'][i]}"></textarea>`).join('')}<p class="fineprint">Promises shape reactions. They do not grant resources or make impossible things real. The fuel crisis still needs your attention.</p><p id="campaign-error" role="status"></p><button class="reply-button" type="submit">Begin my presidency →</button></form>`;}
export function campaignPanel(world:World,brief:StaffBrief|undefined,busy:boolean,status:string){
 const context=campaignRules.context(world);if(!context.promises.length)return '';
 const options=brief?.choices??context.promises.flatMap((_,index)=>campaignRules.options(world,index).map(o=>({index,action:o.id,title:o.title,line:o.title})));
 return `<section class="campaign-panel"><div class="campaign-heading"><span class="eyebrow">YOUR PROMISES · ON THE RECORD</span><button id="refresh-staff" ${busy?'disabled':''}>${busy?'Staff is reviewing…':'Refresh briefing ↻'}</button></div><p class="speech">${e(brief?.line??'Your promises are public claims, not completed projects. We can clarify them, study realistic alternatives, withdraw them, or keep repeating them. Reality will not automatically cooperate.')}</p><p class="fineprint" role="status">${e(status)}</p>${brief?`<div class="pnn-banner"><b>PNN</b> ${e(brief.pnn)}</div>`:''}${context.promises.map((promise,index)=>`<article class="promise-card"><small>PROMISE ${index+1}</small><h3>“${e(promise)}”</h3><p class="fineprint">${e(context.history.filter(h=>h.index===index).map(h=>`Day ${h.day}: ${h.action.replace('_',' ')} — ${h.line}`).join(' • ')||'Public promise · no action taken')}</p><div class="choices">${options.filter(o=>o.index===index).map(o=>{const rule=campaignRules.options(world,index).find(r=>r.id===o.action)!;return `<button class="choice" data-promise="${index}" data-promise-action="${o.action}" ${busy||rule.blocked?'disabled':''}><span>↗</span><span><strong>${e(o.title)}</strong><span class="reply-preview">${e(o.line)}</span><small>${e(rule.blocked??rule.hint)}</small></span></button>`;}).join('')}</div></article>`).join('')}<p class="fineprint">Responses stay in today; choose End day at your desk when the agenda is complete. The history records actions, not automatic fulfillment.</p></section>`;
}
