import {promiseOwnerMarkup} from './cabinet-promises.ts';
import {pressQuestionsMarkup} from './press-questions.ts';
import {congressRules} from '../server/src/congress/congress.ts';
import type {World} from '../shared/schemas/oil-crisis.ts';
import type {StaffBrief} from '../server/src/ai/staff.ts';
import {campaignRules} from '../server/src/campaign/campaign.ts';
import {escapeHtml as e} from './conversation.ts';
import {presidentNameFields} from './president-setup.ts';
export function campaignOpening(){return `<span class="case-tag">BEFORE THE INAUGURATION</span><h2>Three promises.<br>An entire presidency.</h2><p class="speech">What did you promise Freedoma? Be ambitious, practical, or spectacularly unreasonable. The world will remember—and reality gets a vote.</p><form id="campaign-form">${presidentNameFields('president')}${[0,1,2].map(i=>`<label for="promise-${i}">Campaign promise ${i+1}</label><textarea id="promise-${i}" required minlength="5" maxlength="240" rows="2" placeholder="${['Unicorns at every school','Affordable fuel for everyone','Make public transport reliable'][i]}"></textarea>`).join('')}<p class="fineprint">Promises shape reactions. They do not grant resources or make impossible things real. The fuel crisis still needs your attention.</p><p id="campaign-error" role="status"></p><button class="reply-button" type="submit">Begin my presidency →</button></form>`;}
export function campaignPanel(world:World,brief:StaffBrief|undefined,busy:boolean,status:string){
 const context=campaignRules.context(world);if(!context.promises.length)return '';
 const options=brief?.choices??context.promises.flatMap((_,index)=>campaignRules.options(world,index).map(o=>({index,action:o.id,title:o.title,line:o.title})));
 return `<section class="campaign-panel"><div class="campaign-heading"><span class="eyebrow">YOUR PROMISES · ON THE RECORD</span><button id="refresh-staff" ${busy?'disabled':''}>${busy?'Staff is reviewing…':'Refresh briefing ↻'}</button></div><p class="speech">${e(brief?.line??'Your promises are public claims, not completed projects. Introduce a bill, negotiate support, and win both chamber votes to fulfill each promise. You can also fund a feasibility study or make a public statement.')}</p><p class="fineprint" role="status">${e(status)}</p>${pressQuestionsMarkup(world,brief)}${context.promises.map((promise,index)=>`<article class="promise-card"><small>PROMISE ${index+1}</small><h3>“${e(promise)}”</h3>${promiseOwnerMarkup(world,index)}${promiseLegislation(world,index)}<p class="fineprint">${e(context.history.filter(h=>h.index===index).map(h=>`Day ${h.day}: ${h.action.replace('_',' ')} — ${h.line}`).join(' • ')||'Public promise · no action taken')}</p><details class="promise-statements"><summary>Studies and public statements</summary><div class="choices">${options.filter(o=>o.index===index).map(o=>{const rule=campaignRules.options(world,index).find(r=>r.id===o.action)!;return `<button class="choice" data-promise="${index}" data-promise-action="${o.action}" ${busy||rule.blocked?'disabled':''}><span>↗</span><span><strong>${e(o.title)}</strong><span class="reply-preview">${e(o.line)}</span><small>${e(rule.blocked??rule.hint)}</small></span></button>`;}).join('')}</div></details></article>`).join('')}<p class="fineprint">Responses stay in today; choose End day at your desk when the agenda is complete. The history records actions, not automatic fulfillment.</p></section>`;
}

export function promiseLegislation(world:World,index:number){
 const bill=congressRules.bill(world,index),introduced=congressRules.records(world,index).length>0;
 const acted=world.events.some(e=>e.after.day===world.state.day&&e.congress?.kind==='action');
 return `<div class="promise-legislation"><b>${bill.authorized?'Promise fulfilled':bill.passed.length?'Passed one chamber · one to go':introduced?'Bill in Congress':'Ready for legislative action'}</b><p>${bill.authorized?'Both chambers have approved this promise.':introduced?'Negotiate conditions and call each chamber’s vote.':'Put this promise before Congress, then build a majority in both chambers.'}</p><button class="reply-button" data-promise-bill="${index}" ${!introduced&&(acted||world.state.day>30)?'disabled':''}>${bill.authorized?'Review approved bill →':introduced?'Negotiate bill / Call vote →':'Introduce bill →'}</button>${!introduced&&acted?'<small>Today’s congressional action is used. You can introduce this bill tomorrow.</small>':''}<small>Legislative actions count toward today’s public agenda. Opening Congress alone does not.</small></div>`;
}
