import {congressControls,congressVoteReport} from './congress-controls.ts';
import type {World} from '../shared/schemas/oil-crisis.ts';
import {congressRules,chambers} from '../server/src/congress/congress.ts';
import type {Chamber,CongressAction} from '../server/src/congress/congress.ts';
import {actInCongress} from '../server/src/world/oil-crisis.ts';
import {validateCongressVoice} from '../server/src/ai/congress.ts';
import type {CongressVoice} from '../server/src/ai/congress.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createCongressPanel(getWorld:()=>World,commit:(world:World)=>void,isActive:()=>boolean){
 let chamber:Chamber='house',index=0,voice:CongressVoice|undefined,busy=false,context='',epoch=0,status='Offline caucus positions';let selectedApproach='';let host:HTMLElement;
 function render(target:HTMLElement){host=target;const world=getWorld(),promises=congressRules.promises(world);if(!promises.length){host.innerHTML='<h2>Your Congress awaits a platform.</h2><p>This older presidency has no three-promise campaign. Start a new presidency to take promises through Congress.</p>';return;}
 const bill=congressRules.bill(world,index),tally=congressRules.tally(world,index,chamber),options=congressRules.options(world,index,chamber),body=chambers.find(c=>c.id===chamber)!;
 host.innerHTML=`<span class="case-tag">CONGRESS OF FREEDOMA</span><h2>Two chambers.<br>Several strong opinions.</h2><p class="speech">Win a majority in both chambers to fulfill a campaign promise. One congressional action per day; discussion and switching chambers are free.</p><label for="congress-promise">Promise before Congress</label><select id="congress-promise">${promises.map((p,i)=>`<option value="${i}" ${index===i?'selected':''}>${i+1}. ${esc(p)}</option>`).join('')}</select><div class="platform-tabs">${chambers.map(c=>`<button data-chamber="${c.id}" aria-pressed="${chamber===c.id}" class="${chamber===c.id?'active':''}">${c.name}${bill.passed.includes(c.id)?' ✓':''}</button>`).join('')}</div><h3>${body.name}</h3><p class="fineprint">${body.description} · ${tally.seats} seats</p><div class="note"><b>${bill.authorized?'PROMISE FULFILLED · BOTH CHAMBERS APPROVED':bill.passed.includes(chamber)?'THIS CHAMBER HAS PASSED THE PLAN':'PROJECTED VOTE'} · ${tally.yes} yes / ${tally.seats-tally.yes} no</b><br>${tally.needed} yes votes needed. ${bill.authorized?'Credit is earned for the approved promise; no magical resources are created.':'Support reflects the selected promise and your negotiated conditions.'}<div class="voter-bar" role="meter" aria-label="Projected yes votes" aria-valuemin="0" aria-valuemax="${tally.seats}" aria-valuenow="${tally.yes}"><span style="width:${tally.yes/tally.seats*100}%"></span></div></div>
 <div class="bill-plan"><b>Negotiated conditions</b><p>${bill.amendments.map(a=>({costing:'Costed implementation plan',benefits:'Local benefit requirements',oversight:'Independent oversight'}[a]??a)).join(' · ')||'None yet — choose an approach below, or test support with a vote.'}</p></div>${congressVoteReport(world,index,chamber)}
 <div class="social-live"><span role="status">${busy?'The caucuses are debating…':esc(status)}</span><button id="congress-refresh" ${busy?'disabled':''}>Hear the debate ↻</button></div><div class="congress-voices">${tally.voices.map(v=>`<article class="congress-voice"><div><b>${v.name}</b><small>${v.party} · ${v.yes}/${v.seats} projected yes</small></div><p>${esc(voice?.voices.find(x=>x.id===v.id)?.line??`${v.support>=50?'We are leaning toward supporting this.':'You have not convinced our caucus yet.'} Our priority is ${v.priority.toLowerCase()}. ${v.id==='free'?'A slogan is not an audit trail.':v.id==='banner'?'Our districts expect more than a commemorative ribbon.':'Put the practical plan on the table.'}`)}</p></article>`).join('')}</div>
 ${congressControls(world,index,chamber,voice,selectedApproach)}<p id="congress-error" role="alert"></p><details class="bill-history"><summary>Congressional record</summary>${congressRules.records(world,index).map(r=>`<p>${r.chamber==='house'?'People’s House':'Council of States'} · ${r.action}${r.passed!==undefined?` · ${r.passed?'PASSED':'FAILED'}`:''}</p>`).join('')||'<p>No actions yet.</p>'}</details><p class="aside-bottom">Starting caucus positions are randomized once per presidency and saved. AI supplies the debate; recorded rules determine votes. Amendments reopen previous approvals. Preparation costs are not delivery funding.</p>`;
 host.querySelector<HTMLSelectElement>('#congress-promise')!.onchange=e=>{index=Number((e.target as HTMLSelectElement).value);voice=undefined;context='';epoch++;busy=false;render(host);};
 host.querySelectorAll<HTMLButtonElement>('[data-chamber]').forEach(b=>b.onclick=()=>{chamber=b.dataset.chamber as Chamber;voice=undefined;context='';epoch++;busy=false;render(host);});
 const approach=host.querySelector<HTMLSelectElement>('#congress-approach');if(approach)approach.onchange=()=>{selectedApproach=approach.value;render(host);};
 host.querySelector<HTMLButtonElement>('#congress-refresh')!.onclick=()=>void refresh(true);
 host.querySelectorAll<HTMLButtonElement>('[data-congress-action]').forEach(b=>b.onclick=()=>{try{const action=b.dataset.congressAction as CongressAction;const next=actInCongress(getWorld(),index,chamber,action);epoch++;busy=false;voice=undefined;context='';commit(next);}catch(error){host.querySelector('#congress-error')!.textContent=error instanceof Error?error.message:'Action unavailable';}});
 void refresh();
 }
 async function refresh(force=false){const world=getWorld(),key=JSON.stringify([world.events,index,chamber]);if((context===key&&!force)||busy)return;context=key;busy=true;const token=++epoch,promiseIndex=index,chamberId=chamber;render(host);
 try{const r=await fetch(`/api/congress/${chamberId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:world.events,promise:promiseIndex}),signal:AbortSignal.timeout(48000)});const data=await r.json();if(token!==epoch)return;if(data.mode!=='claude')throw Error(data.reason??data.error??'AI debate unavailable');voice=validateCongressVoice(data.voice,world,promiseIndex,chamberId);status='Claude · Three caucus voices';}
 catch(error){if(token!==epoch)return;voice=undefined;status=error instanceof Error?error.message:'Offline caucus positions';}
 if(token!==epoch)return;busy=false;if(isActive()&&JSON.stringify([getWorld().events,index,chamber])===key)render(host);
 }
 return {render,selectPromise(value:number,targetChamber:Chamber='house'){index=value;chamber=targetChamber;epoch++;busy=false;voice=undefined;context='';selectedApproach='';},reset(){epoch++;busy=false;voice=undefined;context='';index=0;chamber='house';selectedApproach='';}};
}
