import type {World} from '../shared/schemas/oil-crisis.ts';
import {congressRules} from '../server/src/congress/congress.ts';
import type {Chamber} from '../server/src/congress/congress.ts';
import type {CongressVoice} from '../server/src/ai/congress.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function congressControls(world:World,index:number,chamber:Chamber,voice?:CongressVoice,selected?:string){
 const options=congressRules.options(world,index,chamber).filter(o=>o.id!=='draft'),negotiations=options.filter(o=>o.id!=='vote'&&o.id!=='introduce'),vote=options.find(o=>o.id==='vote'),bill=congressRules.bill(world,index);
 const active=negotiations.find(o=>o.id===selected)??negotiations.find(o=>!o.blocked)??negotiations[0];
 return `<section class="congress-controls"><h3>Negotiate this promise</h3><p>${esc(bill.promise)}</p>${negotiations.length?`<label for="congress-approach">Choose your approach</label><select id="congress-approach">${negotiations.map(o=>`<option value="${o.id}" ${active?.id===o.id?'selected':''}>${esc(voice?.replies.find(r=>r.id===o.id)?.title??o.title)} · F$${o.cost}</option>`).join('')}</select><p class="note">${esc(active?.blocked??active?.hint??'')}</p><button class="reply-button" data-congress-action="${active!.id}" ${active?.blocked?'disabled':''}>Negotiate selected option →</button>`:'<p>All available concessions are included in this promise.</p>'}<button class="reply-button congress-vote" data-congress-action="vote" ${!vote||vote.blocked?'disabled':''}>${bill.passed.includes(chamber)?'This chamber has approved ✓':'Call vote →'}</button><p class="fineprint">${esc(vote?.blocked??(bill.passed.includes(chamber)?'Secure the other chamber’s approval to fulfill the promise.':'Vote on the current promise and negotiated conditions. A failed vote records the result and uses today’s congressional action.'))}</p></section>`;
}
export function congressVoteReport(world:World,index:number,chamber:Chamber){const report=congressRules.voteReport(world,index,chamber);if(!report)return '';
 return `<section class="congress-result ${report.passed?'passed':'failed'}" role="status"><h3>${report.passed?'Vote passed':'Vote failed'} · Day ${report.day}</h3><p><b>${report.yes} yes · ${report.seats-report.yes} no</b> · ${report.needed} yes needed.</p>${!report.passed?`<p>You fell short by <b>${report.shortfall} ${report.shortfall===1?'vote':'votes'}</b>. Here is where support was missing:</p>`:'<p>This chamber approved the promise. Both chambers must approve the same version for fulfillment.</p>'}<ul>${report.voices.map(v=>`<li><b>${v.party}: ${v.yes} yes / ${v.no} no</b>${!report.passed?`<br>${esc(v.reason)}`:''}</li>`).join('')}</ul>${report.changedSinceVote?'<p>The promise has been amended since this vote. The projection above shows the current support; earlier approvals were reopened.</p>':''}${!report.passed?'<p>Use the negotiation dropdown to address these concerns, then call another vote on a later day. Check the live projection before voting again.</p>':''}</section>`;
}
