import type {World} from '../shared/schemas/oil-crisis.ts';
import {applyStrategic,strategicState,strategicKey,currentStrategicTurn,strategicCandidates,strategicChoices,offlineStrategicVoice,validateStrategicVoice,securityOptions,signingBlocker,diplomaticSettled,complianceRisk,treatySummary,stageLabel,STRATEGIC_BALANCE} from '../server/src/diplomacy/strategic.ts';
import type {SecurityOrder} from '../server/src/diplomacy/strategic-types.ts';
import type {StrategicCommand} from '../server/src/diplomacy/strategic.ts';
import {petrovTurn} from '../server/src/diplomacy/petrov.ts';
import {portrait} from './portraits.ts';
import {escapeHtml as e} from './conversation.ts';
import './strategic-diplomacy.css';
export function strategicReportsMarkup(world:World,source:'PNN'|'BULL'){
 const reports=world.events.flatMap(event=>(event.strategic?.reports??[]).filter(r=>r.source===source).map(r=>({...r,day:event.after.day}))).reverse();
 return reports.length?`<section class="strategic-news" aria-label="${source} strategic developments">${reports.slice(0,10).map(r=>`<article class="news-card"><span class="case-tag">${source} · DAY ${r.day} · ${r.certainty==='confirmed'?'CONFIRMED':'UNVERIFIED REPORT'}</span><h3>${e(r.headline)}</h3><p>${e(r.facts)}</p><button class="text-button" data-open-strategic>Open diplomacy and security →</button></article>`).join('')}</section>`:'';
}
export function strategicMarkup(world:World,busy=false,status='',confirmation?:StrategicCommand){
 const s=strategicState(world)!;
 const turn=currentStrategicTurn(world),record=turn?.strategic?.command,voice=record?.kind==='turn'?record.voice:undefined;
 const candidate=voice?strategicCandidates(world).find(c=>c.id===voice.candidate):undefined;
 const legal=voice?strategicChoices(world,voice.candidate):[];
 const settled=diplomaticSettled(world),finished=world.state.day>30,t=s.treaty,spot=petrovTurn(world);
 const history=world.events.filter(event=>event.strategic?.command.kind==='turn'||event.strategic?.command.kind==='reply').slice(-8);
 const activeOrders=[s.sanctionsUntil>=world.state.day+1?`Sanctions through day ${s.sanctionsUntil}`:'',s.readinessUntil>=world.state.day+1?`Readiness through day ${s.readinessUntil}`:'',s.aidUntil>=world.state.day+1?`Bellara support through day ${s.aidUntil}`:'',s.deploymentUntil>=world.state.day+1?`Deployment through day ${s.deploymentUntil}`:''].filter(Boolean);
 let confirmationHtml='';
 if(confirmation){
  const order=confirmation.kind==='order'?securityOptions(world).find(o=>o.id===confirmation.order):undefined;
  const sign=confirmation.kind==='sign'&&candidate;
  const summary=sign?treatySummary(candidate.terms):order?`${order.title}. F$${order.cost}${order.oil?` plus ${order.oil} barrels`:''}. ${order.hint}`:confirmation.kind==='spot'?`${spot.quantity} barrels delivered now for F$${spot.quantity*spot.unitPrice}. No territorial commitment.`:'Suspend future obligations. Past shipments and payments remain completed. Trust and relations deteriorate.';
  const incompatible=order&&t?.status==='active'&&((t.terms.restraint&&['aid','deployment'].includes(order.id))||(order.id==='sanctions'&&t.terms.quantity>0));
  confirmationHtml=`<section class="strategic-confirm" role="region" aria-label="Review commitment" tabindex="-1"><h3>Review before you commit</h3><p>${e(summary)}</p>${sign?`<p><b>Due now:</b> F$${candidate.terms.observers?STRATEGIC_BALANCE.observerCost:0} for monitoring.<br><b>Scheduled:</b> F$${candidate.terms.quantity*candidate.terms.price} per day at the next three day transitions, ending day ${world.state.day+3}. ${world.state.day+3>30?'The election stops further gameplay; remaining obligations are shown on the record.':''}</p><p>Agreed clauses become binding only when you sign. Verification and delivery can fail; review the risk indicators above.</p>`:''}${incompatible?'<p class="strategic-warning">This order conflicts with your signed agreement and will suspend it.</p>':''}<div class="strategic-confirm-actions"><button class="reply-button" id="strategic-confirm">${sign?'Sign this agreement':order?'Authorize this order':confirmation.kind==='spot'?'Confirm purchase':'Suspend agreement'}</button><button class="text-button" id="strategic-cancel">Keep negotiating / Cancel</button></div></section>`;
 }
 return `<div class="call-heading"><div class="portrait">${portrait('petrov')}</div><div><p class="speaker-name">Viktor Petrov</p><span class="speaker-role">PETROVIA · TRADE & SECURITY</span><span class="call-status">${busy?'Considering your proposal…':voice?.source==='claude'?'Claude · Recorded diplomatic turn':'Recorded diplomacy · Offline support available'}</span></div></div>
 <div class="strategic-situation"><b>${e(stageLabel[s.stage])}</b><span>${s.homeland==='safe'?'No current threat to Freedoma':s.homeland==='threatened'?'Freedoma has been threatened':'Attack on Freedoma recorded'}</span><small>Agreement: ${e(complianceRisk(world).level)} · ${t?.status==='active'&&t.terms.observers?'Independent observers active':s.suspectedBreachDay?'Confirmation pending':'No active observer mandate'}</small>${s.suspectedBreachDay?'<p class="strategic-warning">Troop-movement report is unverified. Confirmation is due at the next day transition.</p>':''}${activeOrders.length?`<p>${activeOrders.map(e).join(' · ')}</p>`:''}</div>
 <p class="fineprint" role="status">${e(status)}</p><div class="strategic-advisers"><button class="text-button" data-strategic-adviser="state">Consult State</button><button class="text-button" data-strategic-adviser="defense">Consult Defense</button><button class="text-button" data-strategic-adviser="treasury">Consult Treasury</button><button class="text-button" id="strategic-ai">AI settings</button></div>
 ${t?`<section class="strategic-treaty"><span class="eyebrow">SIGNED AGREEMENT · ${e(t.status.toUpperCase())}</span><p>${e(treatySummary(t.terms))}</p><p>${e(t.reason)}</p><small>Through day ${t.throughDay} · Delivered ${t.delivered} barrels · Paid F$${t.paid}</small><p class="fineprint">${e(s.lastDelivery)}</p>${t.status==='active'?`<button class="text-button" id="strategic-suspend" ${settled||finished?'disabled':''}>Review suspension of this agreement</button>`:''}</section>`:''}
 ${settled||finished?`<p class="note">${finished?'Your term has ended. Diplomatic history remains available.':'Today’s diplomatic position is recorded. Security orders remain separate; continue diplomacy tomorrow.'}</p>`:`${voice?`<div class="chat-bubble current" tabindex="-1"><small>PETROV · PRIVATE REPLY</small><p>${e(voice.line)}</p></div>`:`<p class="speech">${busy?'Petrov is considering his priorities and your last proposal…':'Open the secure channel to hear his position.'}</p>`}${candidate?`<section class="strategic-terms"><h3>Terms on the table</h3><p class="fineprint">Agreed in principle is not a signed commitment.</p><ul>${candidate.clauses.map(c=>`<li class="${c.accepted?'agreed':'disputed'}"><span aria-hidden="true">${c.accepted?'✓':'!'}</span><div><b>${e(c.label)}</b><small>${e(c.owner)} · ${c.accepted?'Agreed in principle':`Disputed: ${e(c.reason)}`}</small></div></li>`).join('')}</ul><button class="reply-button" id="strategic-review" ${signingBlocker(world,voice!.candidate)?'disabled':''}>Review agreement before signing →</button>${signingBlocker(world,voice!.candidate)?`<p class="fineprint">${e(signingBlocker(world,voice!.candidate)!)}</p>`:''}</section>`:''}${confirmationHtml}<div class="choices">${voice?.replies.map(reply=>{const action=legal.find(c=>c.id===reply.id)!;return `<button class="choice" data-strategic-reply="${e(reply.id)}" ${busy?'disabled':''}><span>↗</span><span><strong>${e(reply.title)}</strong><span class="reply-preview">“${e(reply.line)}”</span><small>${action.kind==='proposal'?`Proposed terms: ${e(treatySummary(action.terms))}`:action.kind==='question'?'Ask a question; no cost or agreement.':'Settle today’s diplomatic position without a new deal.'}</small></span></button>`;}).join('')??''}</div>${busy?'<button class="text-button" id="strategic-offline">Continue this turn offline</button>':''}<button class="text-button" id="strategic-end-call">End today’s talks without a new deal</button>`}
 ${settled||finished?confirmationHtml:''}
 <details class="strategic-orders" data-strategic-disclosure="orders"><summary>Presidential strategy · One security order per day</summary><p class="fineprint">These are strategic orders, not battlefield commands. Orders require your authorization. The election remains the end of the term.</p>${securityOptions(world).map(o=>`<article><b>${e(o.title)}</b><p>F$${o.cost}${o.oil?` + ${o.oil} barrels`:''} · ${e(o.hint)}</p><button class="text-button" data-strategic-order="${o.id}" ${o.blocked?'disabled':''}>Review order →</button>${o.blocked?`<small>${e(o.blocked)}</small>`:''}</article>`).join('')}</details>
 <details class="strategic-orders" data-strategic-disclosure="spot"><summary>One-time oil purchase</summary><p>${spot.quantity} barrels · F$${spot.unitPrice}/barrel · F$${spot.quantity*spot.unitPrice} total.</p><button class="text-button" id="strategic-spot" ${settled||finished||s.sanctionsUntil>=world.state.day+1||world.state.treasury<spot.quantity*spot.unitPrice||spot.quantity<=0?'disabled':''}>Review one-time purchase →</button></details>
 <details class="call-history" data-strategic-disclosure="history"><summary>Earlier in this negotiation</summary>${history.map(event=>{const command=event.strategic!.command;if(command.kind==='turn')return `<div class="chat-bubble"><small>PETROV · DAY ${event.after.day}</small><p>${e(command.voice.line)}</p></div>`;if(command.kind==='reply'){const prior=world.events.find(x=>x.id===command.turnId)?.strategic?.command;return `<div class="chat-bubble player"><small>YOU · DAY ${event.after.day}</small><p>${e(prior?.kind==='turn'?prior.voice.replies.find(r=>r.id===command.choiceId)?.line??'Proposal recorded':'Proposal recorded')}</p></div>`;}return '';}).join('')||'<p>No new exchanges yet. Previous oil deals remain in the public record.</p>'}</details>
 <p class="aside-bottom">Discussion changes the proposal, not the world. Review and sign commitments explicitly. End day resolves supply, compliance, escalation, and domestic consumption.</p><button class="text-button" id="strategic-leave">Back to my desk →</button>`;
}
export function createStrategicPanel(getWorld:()=>World,commit:(next:World,publicChange:boolean)=>void,isActive:()=>boolean,actions:{leave():void;adviser(id:string):void;ai():void}){
 let host:HTMLElement|undefined,busy=false,epoch=0,status='',confirmation:StrategicCommand|undefined,confirmationContext='';
 function save(command:StrategicCommand){const next=applyStrategic(getWorld(),command);commit(next,!['turn','reply','init','end_call'].includes(command.kind));}
 function confirm(command:StrategicCommand){confirmation=command;confirmationContext=strategicKey(getWorld());render(host!);host!.querySelector<HTMLElement>('.strategic-confirm')?.focus();host!.querySelector('.strategic-confirm')?.scrollIntoView({block:'nearest'});}
 function run(command:StrategicCommand){try{epoch++;busy=false;confirmation=undefined;save(command);status='Decision recorded.';if(isActive())render(host!);}catch(error){status=error instanceof Error?error.message:'Diplomatic action unavailable.';if(host&&isActive())render(host);}}
 async function ensureTurn(){
  const world=getWorld();if(busy||currentStrategicTurn(world)||world.state.day>30||diplomaticSettled(world))return;
  const key=strategicKey(world),token=++epoch;busy=true;status='Petrov is considering the exact proposal.';if(host&&isActive())render(host);
  let voice;
  try{const response=await fetch('/api/strategic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:world.events}),signal:AbortSignal.timeout(48000)});const result=await response.json();if(token!==epoch)return;if(key!==strategicKey(getWorld())){busy=false;if(host&&isActive())render(host);return;}if(result.mode!=='claude')throw Error(result.reason??'Offline');voice=validateStrategicVoice(result.voice,getWorld());status='Claude reply saved. Reopening the call keeps these terms.';}
  catch{if(token!==epoch)return;if(key!==strategicKey(getWorld())){busy=false;if(host&&isActive())render(host);return;}voice=offlineStrategicVoice(getWorld());status='Offline diplomatic reply saved. New exchanges will try Claude again.';}
  if(token!==epoch)return;busy=false;
  try{save({kind:'turn',context:key,voice:voice!});}catch(error){status=error instanceof Error?error.message:'Reply became stale.';}
  if(host&&isActive()){render(host);const line=host.querySelector<HTMLElement>('.current');line?.focus({preventScroll:true});line?.scrollIntoView({block:'nearest'});}
 }
 function render(target:HTMLElement){host=target;const world=getWorld();if(confirmationContext!==strategicKey(world))confirmation=undefined;
  const expanded=[...host.querySelectorAll<HTMLDetailsElement>('[data-strategic-disclosure][open]')].map(el=>el.dataset.strategicDisclosure);
  host.innerHTML=strategicMarkup(world,busy,status,confirmation);
  host.querySelectorAll<HTMLDetailsElement>('[data-strategic-disclosure]').forEach(el=>el.open=expanded.includes(el.dataset.strategicDisclosure));
  const bind=(selector:string,fn:()=>void)=>{const el=host!.querySelector<HTMLButtonElement>(selector);if(el)el.onclick=fn;};
  bind('#strategic-leave',actions.leave);bind('#strategic-ai',actions.ai);
  host.querySelectorAll<HTMLButtonElement>('[data-strategic-adviser]').forEach(b=>b.onclick=()=>actions.adviser(b.dataset.strategicAdviser!));
  host.querySelectorAll<HTMLButtonElement>('[data-strategic-reply]').forEach(b=>b.onclick=()=>run({kind:'reply',turnId:currentStrategicTurn(getWorld())!.id,choiceId:b.dataset.strategicReply!}));
  host.querySelectorAll<HTMLButtonElement>('[data-strategic-order]').forEach(b=>b.onclick=()=>confirm({kind:'order',order:b.dataset.strategicOrder as SecurityOrder}));
  bind('#strategic-review',()=>confirm({kind:'sign',turnId:currentStrategicTurn(getWorld())!.id}));
  bind('#strategic-spot',()=>confirm({kind:'spot'}));bind('#strategic-suspend',()=>confirm({kind:'suspend'}));
  bind('#strategic-end-call',()=>run({kind:'end_call'}));
  bind('#strategic-cancel',()=>{confirmation=undefined;render(host!);});
  bind('#strategic-confirm',()=>{if(confirmation&&confirmationContext===strategicKey(getWorld()))run(confirmation);});
  bind('#strategic-offline',()=>{epoch++;busy=false;status='Offline diplomatic reply saved.';try{save({kind:'turn',context:strategicKey(getWorld()),voice:offlineStrategicVoice(getWorld())});}catch(error){status=String(error);}render(host!);});
  void ensureTurn();
 }
 return {render,reset(){epoch++;busy=false;confirmation=undefined;status='';}};
}
